h0=figure('toolbar','none',...
    'units','normalized',...
    'position',[0.2 0.2 0.6 0.5],...
    'name','change cure color');
h1=axes('parent',h0,...
     'units','normalized',...
    'position',[0.1 0.4 0.8 0.5],...
    'visible','on');
x=0:0.1:5*pi;
k=plot(x,sin(x),'-*');
xlabel('自变量X');
ylabel('函数值');
title('改变图像颜色（Y=sin(X)）');
p1=uicontrol('parent',h0,...
    'style','pushbutton',...
    'backgroundcolor','r',...
     'units','normalized',...
    'position',[0.1 0.1 0.15 0.1],...
    'callback','set(k,''color'',''r'')');
p2=uicontrol('parent',h0,...
    'style','pushbutton',...
    'backgroundcolor','g',...
     'units','normalized',...
    'position',[0.3 0.1 0.15 0.1],...
    'callback','set(k,''color'',''g'')');
p3=uicontrol('parent',h0,...
    'style','pushbutton',...
    'backgroundcolor','b',...
     'units','normalized',...
    'position',[0.5 0.1 0.15 0.1],...
    'callback','set(k,''color'',''b'')');
p4=uicontrol('parent',h0,...
    'style','pushbutton',...
    'fontsize',20,...
    'fontweight','demi',...
    'string','关闭',...
     'units','normalized',...
    'position',[0.7 0.1 0.2 0.15],...
    'callback','close');
t1=uicontrol('parent',h0,...
    'style','text',...
    'string','红色',...
    'fontsize',12,...
    'fontweight','demi',...
     'units','normalized',...
    'position',[0.1 0.2 0.15 0.1]);
t2=uicontrol('parent',h0,...
    'style','text',...
    'string','绿色',...
    'fontsize',12,...
    'fontweight','demi',...
     'units','normalized',...
    'position',[0.3 0.2 0.15 0.1]);
t3=uicontrol('parent',h0,...
    'style','text',...
    'string','蓝色',...
    'fontsize',12,...
    'fontweight','demi',...
     'units','normalized',...
    'position',[0.5 0.2 0.15 0.1]);