function ex54_11
%创建图形窗口对象
hFig= figure('units','normalize',...
    'position',[0.4 0.4 0.3 0.2]);
%创建uipanel控件
hPanel=uipanel(hFig,...
    'Title','panel',...
    'units','normalize',...
    'position',[0.1 0.1 0.4 0.8]);
%创建radiobutton控件
hRadio1=uicontrol('parent',hPanel,...
    'style','radiobutton',...
    'String','radiobutton1',...
    'units','normalize',...
    'position',[0.1 0.1 0.8 0.2],...
    'value',1);
hRadio2=uicontrol('parent',hPanel,...
    'style','radiobutton',...
    'String','radiobutton2',...
    'units','normalize',...
    'position',[0.1 0.4 0.8 0.2],...
    'value',0);
hRadio2=uicontrol('parent',hPanel,...
    'style','radiobutton',...
    'String','radiobutton3',...
    'units','normalize',...
    'position',[0.1 0.7 0.8 0.2],...
    'value',0);